name: test

on:
  push:
    branches:
      - mainnet
      - testnet
  pull_request:
    branches:
      - mainnet
      - testnet
      - 'feature/*'
      - 'features/*'

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@82dee4ba654bd2146511f85f0d013af94670c4de #1.4.0

      - name: Update package
        run: forge soldeer update

      - name: Run Forge build
        run: |
          forge --version
          forge build
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test
